apiVersion: v1
kind: Deployment
metadata:
  name: nginx
  label: 
    name: prod
spec:
  replicas: 3
  selector:
    matchLabels:
       name: prod
  template:
    container:
      - name:
        image: nginx
        ports:
          - containerPort:80
